const tableAssignments = {
  "dwarakanatha reddy_duvvuru": "Table 1 (Friday) & Table 1 (Saturday)",
  "nageshwar reddy_duvvuru": "Table 1 (Friday) & Table 1 (Saturday)",
  "mario r_capecchi": "Table 1 (Friday) & Table 1 (Saturday)",
  "ashish_jha": "Table 1 (Friday) & Table 1 (Saturday)",
  "bobby_mukkamala": "Table 1 (Friday) & Table 1 (Saturday)",
  "rep. jonathan jackson_jackson": "Table 1 (Friday) & Table 1 (Saturday)",
  "satish_kathula": "Table 1 (Friday) & Table 1 (Saturday)",
  "bhushan_pandya": "Table 2 (Friday) & Table 2 (Saturday)",
  "dr.willie_underwood": "Table 2 (Friday) & Table 2 (Saturday)",
  "mrs.willie_underwood": "Table 2 (Friday) & Table 2 (Saturday)",
  "savan_suri": "Table 2 (Friday) & Table 2 (Saturday)",
  "lyuba_konopasek": "Table 2 (Friday) & Table 2 (Saturday)",
  "humayun_chaudhry": "Table 2 (Friday) & Table 2 (Saturday)",
  "amol_soin": "Table 2 (Friday) & Table 2 (Saturday)",
  "george_abraham": "Table 2 (Friday) & Table 2 (Saturday)",
  "michael_suk": "Table 3 (Friday) & Table 3 (Saturday)",
  "dr. george abraham_abraham": "Table 3 (Friday) & Table 3 (Saturday)",
  "bharat_barai": "Table 3 (Friday) & Table 3 (Saturday)",
  "yeshwant_reddy": "Table 3 (Friday) & Table 3 (Saturday)",
  "navin_nanda": "Table 3 (Friday) & Table 3 (Saturday)",
  "avi singh_gandh": "Table 3 (Friday) & Table 3 (Saturday)",
  "raj_mitra": "Table 3 (Friday) & Table 3 (Saturday)",
  "shilpa_mitra": "Table 3 (Friday) & Table 3 (Saturday)",
  "venkat_sood": "Table 88 (Friday) & Table 88 (Saturday)",
  "debbie_haynes": "Table 88 (Friday) & Table 88 (Saturday)",
  "jayasudha_": "Table 88 (Friday) & Table 88 (Saturday)",
  "akshar_kathula": "Table 99 (Friday) & Table 99 (Saturday)",
  "aneesh_kathula": "Table 99 (Friday) & Table 99 (Saturday)",
  "prema_kathula": "Table 99 (Friday) & Table 99 (Saturday)",
  "ashok_myneni": "Table 99 (Friday) & Table 99 (Saturday)",
  "shervani_": "Table 77 (Friday) & Table 77 (Saturday)",
  "damodar_patel": "Table 77A (Friday) & Table 77A (Saturday)",
  "vasanth_tumu": "Table 77A (Friday) & Table 77A (Saturday)",
  "swarna_kesari": "Table 62 (Friday) & Table 62 (Saturday)",
  "prakash_kesari": "Table 62 (Friday) & Table 62 (Saturday)",
  "hema_gajjela": "Table 61 (Friday) & Table 61 (Saturday)",
  "deepthi_gajjela": "Table 61 (Friday) & Table 61 (Saturday)",
  "aruna_pallam": "Table 77A (Friday) & Table 77A (Saturday)",
  "praveena_pallam": "Table 77A (Friday) & Table 77A (Saturday)",
  "vasantha_tumu": "Table 77A (Friday) & Table 77A (Saturday)",
  "arun_pallam": "Table 77A (Friday) & Table 77A (Saturday)",
  "veena_pallam": "Table 88 (Friday) & Table 88 (Saturday)",
  "vijaya_challa": "Table 88 (Friday) & Table 88 (Saturday)",
  "bharathi_muddasani": "Table 88 (Friday) & Table 88 (Saturday)",
  "raj_grandhi": "Table 88 (Friday) & Table 88 (Saturday)",
  "meera_grandhi": "Table 88 (Friday) & Table 88 (Saturday)",
  "pk_vedanthan": "Table 88 (Friday) & Table 88 (Saturday)",
  "srinivas_adusumili": "Table 4 (Friday) & Table 4 (Saturday)",
  "veda_adusumili": "Table 4 (Friday) & Table 4 (Saturday)",
  "annika_surya": "Table 4 (Friday) & Table 4 (Saturday)",
  "srikanth_paladugu": "Table 4 (Friday) & Table 4 (Saturday)",
  "sirisha_paladugu": "Table 4 (Friday) & Table 4 (Saturday)",
  "vaidika_ravi": "Table 4 (Friday) & Table 4 (Saturday)",
  "vainavi_ravi": "Table 4 (Friday) & Table 4 (Saturday)",
  "teja_paladugu": "Table 4 (Friday) & Table 4 (Saturday)",
  "vidya_kora": "Table 4 (Friday) & Table 4 (Saturday)",
  "vidya-2_kora": "Table 4 (Friday) & Table 4 (Saturday)",
  "arvinder_bir": "Table 5 (Friday) & Table 5 (Saturday)",
  "angelina_bir": "Table 5 (Friday) & Table 5 (Saturday)",
  "navdeep_bir": "Table 5 (Friday) & Table 5 (Saturday)",
  "kunwardeep (richie)_bir": "Table 5 (Friday) & Table 5 (Saturday)",
  "priya_korrapati": "Table 5 (Friday) & Table 5 (Saturday)",
  "divya_navani": "Table 6 (Friday) & Table 6 (Saturday)",
  "syed_ahmed": "Table 6 (Friday) & Table 6 (Saturday)",
  "sushil_jain": "Table 6 (Friday) & Table 6 (Saturday)",
  "ranjita_sengupta": "Table 6 (Friday) & Table 6 (Saturday)",
  "rekha_nair": "Table 6 (Friday) & Table 6 (Saturday)",
  "madhuri_vallabhuni": "Table 7 (Friday) & Table 7 (Saturday)",
  "anil_barri": "Table 7 (Friday) & Table 7 (Saturday)",
  "radhika_rajsheker": "Table 7 (Friday) & Table 7 (Saturday)",
  "srinivas_rajsheker": "Table 7 (Friday) & Table 7 (Saturday)",
  "neela_rajasekhar": "Table 7 (Friday) & Table 7 (Saturday)",
  "rajasekhar_lakkaraj": "Table 7 (Friday) & Table 7 (Saturday)",
  "smitha_bearelly": "Table 7 (Friday) & Table 7 (Saturday)",
  "dilip_bearelly": "Table 7 (Friday) & Table 7 (Saturday)",
  "girish_nagesetty": "Table 7 (Friday) & Table 7 (Saturday)",
  "sarada_nagesetty": "Table 7 (Friday) & Table 7 (Saturday)",
  "anjali_pathak gulati": "Table 8 (Friday) & Table 8 (Saturday)",
  "anil_gulati": "Table 8 (Friday) & Table 8 (Saturday)",
  "sonchita_chakrabarty": "Table 8 (Friday) & Table 8 (Saturday)",
  "amit_chakrabarty": "Table 8 (Friday) & Table 8 (Saturday)",
  "arra_reddy": "Table 8 (Friday) & Table 8 (Saturday)",
  "arra guest_reddy": "Table 8 (Friday) & Table 8 (Saturday)",
  "sashi_kuppala": "Table 8 (Friday) & Table 8 (Saturday)",
  "kavita_jyotula": "Table 8 (Friday) & Table 8 (Saturday)",
  "malti_mehta": "Table 8 (Friday) & Table 8 (Saturday)",
  "praful_mehta": "Table 8 (Friday) & Table 8 (Saturday)",
  "umamaheswari_jonnalagadda": "Table 9 (Friday) & Table 9 (Saturday)",
  "sudhakar_jonnalagadda": "Table 9 (Friday) & Table 9 (Saturday)",
  "bhushan-2_pandya": "Table 3 (Friday) & Table 3 (Saturday)",
  "sujeeth_punnam": "Table 9 (Friday) & Table 9 (Saturday)",
  "meher_medavaram": "Table 9 (Friday) & Table 9 (Saturday)",
  "rama_medavaram": "Table 9 (Friday) & Table 9 (Saturday)",
  "ravindra_kolli": "Table 9 (Friday) & Table 9 (Saturday)",
  "latha_kolli": "Table 9 (Friday) & Table 9 (Saturday)",
  "rammurthy_chirunomula": "Table 9 (Friday) & Table 9 (Saturday)",
  "padmavathi_chirunomula": "Table 9 (Friday) & Table 9 (Saturday)",
  "suresh_k. gupta": "Table 61 (Friday) & Table 61 (Saturday)",
  "soumya_neravetla": "Table 10 (Friday) & Table 10 (Saturday)",
  "surender_neravetla": "Table 10 (Friday) & Table 10 (Saturday)",
  "srinivasa_gokarakonda": "Table 10 (Friday) & Table 10 (Saturday)",
  "sreeni_gangasani md": "Table 10 (Friday) & Table 10 (Saturday)",
  "madhavi_gangasani": "Table 10 (Friday) & Table 10 (Saturday)",
  "syamala_erramilli": "Table 10 (Friday) & Table 10 (Saturday)",
  "parmesh_erramilli": "Table 10 (Friday) & Table 10 (Saturday)",
  "vijitha_reddy": "Table 10 (Friday) & Table 10 (Saturday)",
  "vishnu_reddy": "Table 10 (Friday) & Table 10 (Saturday)",
  "hetal_gor": "Table 11 (Friday) & Table 11 (Saturday)",
  "hetal-2_gor": "Table 11 (Friday) & Table 11 (Saturday)",
  "ram_singh": "Table 11 (Friday) & Table 11 (Saturday)",
  "seema_arora": "Table 11 (Friday) & Table 11 (Saturday)",
  "sandeep_arora": "Table 11 (Friday) & Table 11 (Saturday)",
  "rekha_maurya": "Table 11 (Friday) & Table 11 (Saturday)",
  "vijay_maurya": "Table 11 (Friday) & Table 11 (Saturday)",
  "indresh_venkatarayappa": "Table 11 (Friday) & Table 11 (Saturday)",
  "disha_singahla": "Table 11 (Friday) & Table 11 (Saturday)",
  "lokesh_edara": "Table 11 (Friday) & Table 11 (Saturday)",
  "saroj_gandhi": "Table 12 (Friday) & Table 12 (Saturday)",
  "suresh_mendpara": "Table 12 (Friday) & Table 12 (Saturday)",
  "dipti_mendpara": "Table 12 (Friday) & Table 12 (Saturday)",
  "ramesh_gandhi": "Table 12 (Friday) & Table 12 (Saturday)",
  "srinivas_vengela": "Table 12 (Friday) & Table 12 (Saturday)",
  "mayank_patel": "Table 12 (Saturday only)",
  "arvind_goyal": "Table 31 (Friday) & Table 31 (Saturday)",
  "amitkumar_goyal": "Table 12 (Saturday only)",
  "reena_goyal": "Table 12 (Friday) & Table 12 (Saturday)",
  "sunita_reddy": "Table 12 (Friday) & Table 12 (Saturday)",
  "vemuri s._murthy": "Table 13 (Friday) & Table 13 (Saturday)",
  "bharti_khurana": "Table 13 (Friday) & Table 13 (Saturday)",
  "dp_suresh": "Table 26 (Friday) & Table 26 (Saturday)",
  "amit_govil": "Table 13 (Friday) & Table 13 (Saturday)",
  "indranil_basu-ray": "Table 13 (Friday) & Table 13 (Saturday)",
  "krishan_kumar": "Table 13 (Friday) & Table 13 (Saturday)",
  "surendra_purohit": "Table 13 (Friday) & Table 13 (Saturday)",
  "avinash_gupta": "Table 13 (Friday) & Table 13 (Saturday)",
  "sharma_prabhakar": "Table 13 (Friday) & Table 13 (Saturday)",
  "ami_shah": "Table 13 (Friday) & Table 13 (Saturday)",
  "sreenadha_vattam": "Table 23 (Friday) & Table 23 (Saturday)",
  "thiruvoipati_nandakumar": "Table 14 (Friday) & Table 14 (Saturday)",
  "indira_veerisetty": "Table 14 (Friday) & Table 14 (Saturday)",
  "annapurna_bhat": "Table 14 (Friday) & Table 14 (Saturday)",
  "azeem_sachedina": "Table 14 (Friday) & Table 14 (Saturday)",
  "charles_kannankeril": "Table 14 (Friday) & Table 14 (Saturday)",
  "mary_kannankeril": "Table 14 (Friday) & Table 14 (Saturday)",
  "ritu_agarwal": "Table 14 (Friday) & Table 14 (Saturday)",
  "bikash_agarwal": "Table 14 (Friday) & Table 14 (Saturday)",
  "shyam_allamneni": "Table 15 (Friday) & Table 15 (Saturday)",
  "radhika_allamaneni": "Table 15 (Friday) & Table 15 (Saturday)",
  "challa_jyothi": "Table 15 (Friday) & Table 15 (Saturday)",
  "challa_ajit": "Table 15 (Friday) & Table 15 (Saturday)",
  "suhas_kataveni": "Table 15 (Friday) & Table 15 (Saturday)",
  "shailaja_hari": "Table 15 (Friday) & Table 15 (Saturday)",
  "nagaraja_oruganti": "Table 15 (Friday) & Table 15 (Saturday)",
  "shashank_ponugoti": "Table 15 (Friday) & Table 15 (Saturday)",
  "dr. praveen_kollipara": "Table 15 (Friday) & Table 15 (Saturday)",
  "tejaswini_potlapalli": "Table 15 (Friday) & Table 15 (Saturday)",
  "subrahmanya_bhat": "Table 16 (Friday) & Table 16 (Saturday)",
  "anand_kishore": "Table 16 (Friday) & Table 16 (Saturday)",
  "dr lakshmi_kishore": "Table 16 (Friday) & Table 16 (Saturday)",
  "janak_joshi": "Table 16 (Friday) & Table 16 (Saturday)",
  "anjana_joshi": "Table 16 (Friday) & Table 16 (Saturday)",
  "jyoti_chakote": "Table 16 (Friday) & Table 16 (Saturday)",
  "kirti_vaijinath": "Table 37 (Friday) & Table 37 (Saturday)",
  "ravinder reddy_perati": "Table 16 (Friday) & Table 16 (Saturday)",
  "mohan_mallam": "Table 16 (Friday) & Table 16 (Saturday)",
  "narendra_maheshwari": "Table 16 (Friday) & Table 16 (Saturday)",
  "pradeep_bekal": "Table 17 (Friday) & Table 17 (Saturday)",
  "pratima_bekal": "Table 17 (Friday) & Table 17 (Saturday)",
  "maninder_kalra": "Table 17 (Friday) & Table 17 (Saturday)",
  "harpinder_kalra": "Table 17 (Friday) & Table 17 (Saturday)",
  "amaresh_nath": "Table 17 (Friday) & Table 17 (Saturday)",
  "geeta_nath": "Table 17 (Friday) & Table 17 (Saturday)",
  "dr. rajbir_minhas": "Table 17 (Friday) & Table 17 (Saturday)",
  "renu_kotwal": "Table 17 (Friday) & Table 17 (Saturday)",
  "mamata_narendran": "Table 17 (Friday) & Table 17 (Saturday)",
  "vivek_narendran": "Table 17 (Friday) & Table 17 (Saturday)",
  "lekha_devara": "Table 18 (Friday) & Table 18 (Saturday)",
  "anitha_mandadapu": "Table 18 (Friday) & Table 18 (Saturday)",
  "surender_sandella": "Table 18 (Friday) & Table 18 (Saturday)",
  "sheela_sandella": "Table 18 (Friday) & Table 18 (Saturday)",
  "pradyumna_devara": "Table 18 (Friday) & Table 18 (Saturday)",
  "ravi_ravinuthala": "Table 18 (Friday) & Table 18 (Saturday)",
  "vijaya_reddy": "Table 18 (Friday) & Table 18 (Saturday)",
  "pushpa_pavuluri": "Table 18 (Friday) & Table 18 (Saturday)",
  "yasoda_dev": "Table 18 (Friday) & Table 18 (Saturday)",
  "naveen_devabhaktuni": "Table 18 (Friday) & Table 18 (Saturday)",
  "anita_reddy": "Table 19 (Friday) & Table 19 (Saturday)",
  "m niranjan_reddy": "Table 19 (Friday) & Table 19 (Saturday)",
  "sima_kaneria": "Table 19 (Friday) & Table 19 (Saturday)",
  "rakesh_kaneria": "Table 19 (Friday) & Table 19 (Saturday)",
  "priti_maheshwari": "Table 19 (Friday) & Table 19 (Saturday)",
  "pushpa_rajagopal": "Table 19 (Friday) & Table 19 (Saturday)",
  "dr. rajagopal_holalkere": "Table 19 (Friday) & Table 19 (Saturday)",
  "sarfaraz_ahmad": "Table 19 (Friday) & Table 19 (Saturday)",
  "raafat_ahmad": "Table 19 (Friday) & Table 19 (Saturday)",
  "_": "Table 71 (Friday) & Table 71 (Saturday)",
  "sashi_makam": "Table 20 (Friday) & Table 20 (Saturday)",
  "minaxi_munjapara": "Table 20 (Friday) & Table 20 (Saturday)",
  "sanjeev_gupta": "Table 20 (Friday) & Table 20 (Saturday)",
  "mukta_gupta": "Table 20 (Friday) & Table 20 (Saturday)",
  "ravindra r_kandula": "Table 20 (Friday) & Table 20 (Saturday)",
  "namratha_kandula": "Table 20 (Friday) & Table 20 (Saturday)",
  "sandhya_agochiya": "Table 20 (Friday) & Table 20 (Saturday)",
  "nitin_agochiya": "Table 20 (Friday) & Table 20 (Saturday)",
  "sona_sheth": "Table 20 (Friday) & Table 20 (Saturday)",
  "manish_sheth": "Table 20 (Friday) & Table 20 (Saturday)",
  "udaya_kamath": "Table 21 (Friday) & Table 21 (Saturday)",
  "ramadas_kamath": "Table 21 (Friday) & Table 21 (Saturday)",
  "venkatrao_kamani": "Table 21 (Friday) & Table 21 (Saturday)",
  "venkatrao-2_kamani": "Table 21 (Friday) & Table 21 (Saturday)",
  "lakshmikumari_yella": "Table 21 (Friday) & Table 21 (Saturday)",
  "subbarao_bhimani": "Table 21 (Friday) & Table 21 (Saturday)",
  "kathleen_benson": "Table 21 (Friday) & Table 21 (Saturday)",
  "vijay_jain": "Table 21 (Friday) & Table 21 (Saturday)",
  "subhdeep_virk": "Table 21 (Friday) & Table 21 (Saturday)",
  "venu gopal_bathini": "Table 21 (Friday) & Table 21 (Saturday)",
  "dr. sreedhar_samudrala": "Table 22 (Friday) & Table 22 (Saturday)",
  "kairali_samudrala": "Table 22 (Friday) & Table 22 (Saturday)",
  "shobha_aggarwal": "Table 22 (Friday) & Table 22 (Saturday)",
  "ajay_aggarwal": "Table 22 (Friday) & Table 22 (Saturday)",
  "anou_singhvi": "Table 22 (Friday) & Table 22 (Saturday)",
  "manish_bhandari": "Table 22 (Friday) & Table 22 (Saturday)",
  "narasimha_boorgu": "Table 22 (Friday) & Table 22 (Saturday)",
  "subhashini_boorgu": "Table 22 (Friday) & Table 22 (Saturday)",
  "sudha_parikh": "Table 22 (Friday) & Table 22 (Saturday)",
  "sudhir_parikh": "Table 22 (Friday) & Table 22 (Saturday)",
  "udaya_shivangi": "Table 23 (Friday) & Table 23 (Saturday)",
  "savitha_rajan": "Table 23 (Friday) & Table 23 (Saturday)",
  "thomas_rajan": "Table 23 (Friday) & Table 23 (Saturday)",
  "suresh_gupta": "Table 23 (Friday) & Table 23 (Saturday)",
  "maansi_gupta": "Table 23 (Friday) & Table 23 (Saturday)",
  "shashidhara_murthy": "Table 23 (Friday) & Table 23 (Saturday)",
  "vijay-2_rao": "Table 23 (Friday) & Table 23 (Saturday)",
  "vijay_rao": "Table 23 (Friday) & Table 23 (Saturday)",
  "vasudeva_nalipireddy": "Table 23 (Friday) & Table 23 (Saturday)",
  "dipti_patel": "Table 24 (Friday) & Table 24 (Saturday)",
  "vipul_patel": "Table 24 (Friday) & Table 24 (Saturday)",
  "harish_chandna": "Table 24 (Friday) & Table 24 (Saturday)",
  "manju_sachdev": "Table 24 (Friday) & Table 24 (Saturday)",
  "deepak_kumar": "Table 24 (Friday) & Table 24 (Saturday)",
  "surekha_kumar": "Table 24 (Friday) & Table 24 (Saturday)",
  "sandeep_kapur": "Table 24 (Friday) & Table 24 (Saturday)",
  "sangita_kapur": "Table 24 (Friday) & Table 24 (Saturday)",
  "krishna_samba": "Table 24 (Friday) & Table 24 (Saturday)",
  "umasankar_kakumanu": "Table 24 (Friday) & Table 24 (Saturday)",
  "samyukta_chava": "Table 25 (Friday) & Table 25 (Saturday)",
  "saroj_sharma": "Table 25 (Friday) & Table 25 (Saturday)",
  "madhavi_gorusu": "Table 25 (Friday) & Table 25 (Saturday)",
  "jagdish_gupta": "Table 25 (Friday) & Table 25 (Saturday)",
  "madhu_hooda": "Table 25 (Friday) & Table 25 (Saturday)",
  "raghuveer_annam": "Table 25 (Friday) & Table 25 (Saturday)",
  "vijayalaxmi_annam": "Table 25 (Friday) & Table 25 (Saturday)",
  "ravindra_nath": "Table 25 (Friday) & Table 25 (Saturday)",
  "jayant_jhaveri": "Table 25 (Friday) & Table 25 (Saturday)",
  "neeranjana_jhaveri": "Table 25 (Friday) & Table 25 (Saturday)",
  "venkataramu_krishnamurthy": "Table 26 (Friday) & Table 26 (Saturday)",
  "holenarsipur_ramadas": "Table 26 (Friday) & Table 26 (Saturday)",
  "uma_raju": "Table 26 (Friday) & Table 26 (Saturday)",
  "parneet_sohi": "Table 26 (Friday) & Table 26 (Saturday)",
  "dharmesh_gandhi": "Table 26 (Friday) & Table 26 (Saturday)",
  "raja_chadalavada, md": "Table 26 (Friday) & Table 26 (Saturday)",
  "ashok_penmetsa": "Table 26 (Friday) & Table 26 (Saturday)",
  "samuel_murala": "Table 26 (Friday) & Table 26 (Saturday)",
  "dhananjay_paranjpe": "Table 26 (Friday) & Table 26 (Saturday)",
  "prakash_patel": "Table 27 (Friday) & Table 27 (Saturday)",
  "annu_terkonda, m.d.": "Table 27 (Friday) & Table 27 (Saturday)",
  "murthy_gollamudi": "Table 27 (Friday) & Table 27 (Saturday)",
  "ramakrishna_gollamudi": "Table 27 (Friday) & Table 27 (Saturday)",
  "sreevani_gollamudi": "Table 27 (Friday) & Table 27 (Saturday)",
  "hema_pandrangi": "Table 27 (Friday) & Table 27 (Saturday)",
  "meenakshi_patel": "Table 27 (Friday) & Table 27 (Saturday)",
  "ravinder_gandhi": "Table 27 (Friday) & Table 27 (Saturday)",
  "balbir_gandhi": "Table 27 (Friday) & Table 27 (Saturday)",
  "jayanta t_mukherjee": "Table 27 (Friday) & Table 27 (Saturday)",
  "rajeev_mehta": "Table 28 (Friday) & Table 28 (Saturday)",
  "muralidhar_santapuram": "Table 28 (Friday) & Table 28 (Saturday)",
  "srikanth_sadhu": "Table 28 (Friday) & Table 28 (Saturday)",
  "maya_sachdeva": "Table 28 (Friday) & Table 28 (Saturday)",
  "inderpreet_rangi": "Table 28 (Friday) & Table 28 (Saturday)",
  "kumud_shah": "Table 28 (Friday) & Table 28 (Saturday)",
  "rekha_shah": "Table 28 (Friday) & Table 28 (Saturday)",
  "sushil_mittal": "Table 28 (Friday) & Table 28 (Saturday)",
  "raj_katara": "Table 28 (Friday) & Table 28 (Saturday)",
  "anu_kapur": "Table 28 (Friday) & Table 28 (Saturday)",
  "shyam_vyas": "Table 29 (Friday) & Table 29 (Saturday)",
  "kavita_vyas": "Table 29 (Friday) & Table 29 (Saturday)",
  "ketul_vora": "Table 29 (Friday) & Table 29 (Saturday)",
  "manvesh_sinha": "Table 29 (Friday) & Table 29 (Saturday)",
  "naina_sharma": "Table 29 (Friday) & Table 29 (Saturday)",
  "juhi_chawla": "Table 29 (Friday) & Table 29 (Saturday)",
  "des_bharti": "Table 29 (Friday) & Table 29 (Saturday)",
  "sanjay_agarwal": "Table 29 (Friday) & Table 29 (Saturday)",
  "pooja_malik": "Table 29 (Friday) & Table 29 (Saturday)",
  "rajesh_malik": "Table 29 (Friday) & Table 29 (Saturday)",
  "suresh_sachdeva": "Table 30 (Friday) & Table 30 (Saturday)",
  "harrsha_thirunagari": "Table 30 (Friday) & Table 30 (Saturday)",
  "thirumala_raju": "Table 30 (Friday) & Table 30 (Saturday)",
  "sachchidanand_jha": "Table 30 (Friday) & Table 30 (Saturday)",
  "ajay_chawla": "Table 30 (Friday) & Table 30 (Saturday)",
  "srinivas_jonnala": "Table 30 (Friday) & Table 30 (Saturday)",
  "bellamkonda_kishore": "Table 30 (Friday) & Table 30 (Saturday)",
  "sarvalakshmi_kurella": "Table 30 (Friday) & Table 30 (Saturday)",
  "bhola_rama": "Table 30 (Friday) & Table 30 (Saturday)",
  "swarna_latha": "Table 30 (Friday) & Table 30 (Saturday)",
  "sarla_saujanni": "Table 31 (Friday) & Table 31 (Saturday)",
  "abhijit_roychowdhury": "Table 31 (Friday) & Table 31 (Saturday)",
  "chand_rohatgi": "Table 31 (Friday) & Table 31 (Saturday)",
  "jabbar_zafar": "Table 31 (Friday) & Table 31 (Saturday)",
  "malini_venkatram": "Table 31 (Friday) & Table 31 (Saturday)",
  "renu_goyal": "Table 31 (Friday) & Table 31 (Saturday)",
  "sangeeta_aggarwal": "Table 31 (Friday) & Table 31 (Saturday)",
  "sudheer_polisetty": "Table 31 (Friday) & Table 31 (Saturday)",
  "amitkumar_patel": "Table 31 (Friday) & Table 31 (Saturday)",
  "surbhi_sanathra": "Table 32 (Friday) & Table 32 (Saturday)",
  "mahendra_sanathra": "Table 32 (Friday) & Table 32 (Saturday)",
  "a.b._reddy": "Table 32 (Friday) & Table 32 (Saturday)",
  "vivek_vaid": "Table 32 (Friday) & Table 32 (Saturday)",
  "neena_tapryal": "Table 32 (Friday) & Table 32 (Saturday)",
  "pritam_tapryal": "Table 32 (Friday) & Table 32 (Saturday)",
  "ranjana_sharma": "Table 32 (Friday) & Table 32 (Saturday)",
  "ashok_fulambarker": "Table 32 (Friday) & Table 32 (Saturday)",
  "geetu_pahlajani": "Table 32 (Friday) & Table 32 (Saturday)",
  "narayan s_peddanna": "Table 32 (Friday) & Table 32 (Saturday)",
  "jyoti_sachdeva": "Table 33 (Friday) & Table 33 (Saturday)",
  "shachi_singh": "Table 33 (Friday) & Table 33 (Saturday)",
  "parameswaran_hariharan": "Table 33 (Friday) & Table 33 (Saturday)",
  "lalitha_parameswaran": "Table 33 (Friday) & Table 33 (Saturday)",
  "ajay_kaul": "Table 33 (Friday) & Table 33 (Saturday)",
  "pamposh_kaul": "Table 33 (Friday) & Table 33 (Saturday)",
  "jyoti_mehta": "Table 33 (Friday) & Table 33 (Saturday)",
  "harsh_sachdeva": "Table 33 (Friday) & Table 33 (Saturday)",
  "ina_agrawal": "Table 33 (Friday) & Table 33 (Saturday)",
  "narendra_agrawal": "Table 33 (Friday) & Table 33 (Saturday)",
  "meena_mittal": "Table 34 (Friday) & Table 34 (Saturday)",
  "anurag_tewari": "Table 34 (Friday) & Table 34 (Saturday)",
  "malti_vij": "Table 34 (Friday) & Table 34 (Saturday)",
  "brinder_vij": "Table 34 (Friday) & Table 34 (Saturday)",
  "sakshum_vij": "Table 34 (Friday) & Table 34 (Saturday)",
  "manan_vij": "Table 34 (Friday) & Table 34 (Saturday)",
  "poonam_bhatia": "Table 34 (Friday) & Table 34 (Saturday)",
  "rajeev_bhatia": "Table 34 (Friday) & Table 34 (Saturday)",
  "puneet_bhatla": "Table 34 (Friday) & Table 34 (Saturday)",
  "teena_bhatla": "Table 34 (Friday) & Table 34 (Saturday)",
  "aradhana_pandey": "Table 35 (Friday) & Table 35 (Saturday)",
  "vishal_pandey": "Table 35 (Friday) & Table 35 (Saturday)",
  "preeti_lekhra": "Table 35 (Friday) & Table 35 (Saturday)",
  "siddharth_mathur": "Table 35 (Friday) & Table 35 (Saturday)",
  "kanav_mathur": "Table 35 (Friday) & Table 35 (Saturday)",
  "vivek_batra": "Table 35 (Friday) & Table 35 (Saturday)",
  "ananya_bhatla": "Table 35 (Friday) & Table 35 (Saturday)",
  "vaibhav_bhatla": "Table 35 (Friday) & Table 35 (Saturday)",
  "rupesh_raina": "Table 35 (Friday) & Table 35 (Saturday)",
  "atasu_nayak": "Table 35 (Friday) & Table 35 (Saturday)",
  "renuka_mittal": "Table 36 (Friday) & Table 36 (Saturday)",
  "valji_munjapara": "Table 36 (Friday) & Table 36 (Saturday)",
  "prem_konakondla": "Table 36 (Friday) & Table 36 (Saturday)",
  "chitta_mallik": "Table 36 (Friday) & Table 36 (Saturday)",
  "razia_shaik": "Table 36 (Friday) & Table 36 (Saturday)",
  "sithara_samudrala": "Table 36 (Friday) & Table 36 (Saturday)",
  "neelima_sinha": "Table 36 (Friday) & Table 36 (Saturday)",
  "divya amit_joshi": "Table 36 (Friday) & Table 36 (Saturday)",
  "sahithi_burra": "Table 36 (Friday) & Table 36 (Saturday)",
  "rutva_jani": "Table 36 (Friday) & Table 36 (Saturday)",
  "veeraen_jonnalagadda": "Table 37 (Friday) & Table 37 (Saturday)",
  "bhavya_bommadi": "Table 37 (Friday) & Table 37 (Saturday)",
  "nitin_malepati": "Table 37 (Friday) & Table 37 (Saturday)",
  "neil_oza": "Table 37 (Friday) & Table 37 (Saturday)",
  "sai pavitra_paidimarri": "Table 37 (Friday) & Table 37 (Saturday)",
  "pranay_vaghela": "Table 37 (Friday) & Table 37 (Saturday)",
  "prithwijit_roychowdhury": "Table 37 (Friday) & Table 37 (Saturday)",
  "harshkumar_patel": "Table 37 (Friday) & Table 37 (Saturday)",
  "kashyap_sheth": "Table 37 (Friday) & Table 37 (Saturday)",
  "niti_patel": "Table 38 (Friday) & Table 38 (Saturday)",
  "pooja_kinkhabwala": "Table 38 (Friday) & Table 38 (Saturday)",
  "sheenu_chhabra": "Table 38 (Friday) & Table 38 (Saturday)",
  "kaushik_annam": "Table 38 (Friday) & Table 38 (Saturday)",
  "venu_alapati": "Table 38 (Friday) & Table 38 (Saturday)",
  "shweta_maheshwari": "Table 38 (Friday) & Table 38 (Saturday)",
  "twisha_oza": "Table 38 (Friday) & Table 38 (Saturday)",
  "nik_raju": "Table 38 (Friday) & Table 38 (Saturday)",
  "kinjal_solanki": "Table 39 (Friday) & Table 39 (Saturday)",
  "saurabh_tyagi": "Table 39 (Friday) & Table 39 (Saturday)",
  "zubin_agarwal": "Table 39 (Friday) & Table 39 (Saturday)",
  "swati_kumar": "Table 39 (Friday) & Table 39 (Saturday)",
  "shilpi_kumar": "Table 39 (Friday) & Table 39 (Saturday)",
  "shefali_kothary": "Table 39 (Friday) & Table 39 (Saturday)",
  "vishal_kinkhabwala": "Table 39 (Friday) & Table 39 (Saturday)",
  "ishna_sharma": "Table 39 (Friday) & Table 39 (Saturday)",
  "anil_tumu": "Table 39 (Friday) & Table 39 (Saturday)",
  "shanthan_tumu": "Table 39 (Friday) & Table 39 (Saturday)",
  "sreeni_gangasani": "Table 40 (Friday) & Table 40 (Saturday)",
  "anjali_gulati": "Table 40 (Friday) & Table 40 (Saturday)",
  "rajagopal_holalkere": "Table 40 (Friday) & Table 40 (Saturday)",
  "naimesh_shah": "Table 40 (Friday) & Table 40 (Saturday)",
  "praveen_kollipara": "Table 40 (Friday) & Table 40 (Saturday)",
  "sudha_kora": "Table 40 (Friday) & Table 40 (Saturday)",
  "sunitha_polepalle": "Table 40 (Friday) & Table 40 (Saturday)",
  "ramadas_medavaram": "Table 40 (Friday) & Table 40 (Saturday)",
  "rashmi_pandya": "Table 40 (Friday) & Table 40 (Saturday)",
  "padma_rao": "Table 40 (Friday) & Table 40 (Saturday)",
  "suresh_reddy": "Table 41 (Friday) & Table 41 (Saturday)",
  "leela_reddy": "Table 41 (Friday) & Table 41 (Saturday)",
  "sunil_reddy": "Table 41 (Friday) & Table 41 (Saturday)",
  "parveen_sachedina": "Table 41 (Friday) & Table 41 (Saturday)",
  "shaleen_vira": "Table 41 (Friday) & Table 41 (Saturday)",
  "akhil_patel": "Table 41 (Friday) & Table 41 (Saturday)",
  "pratik_kothary": "Table 41 (Friday) & Table 41 (Saturday)",
  "gautam_kamthan": "Table 41 (Friday) & Table 41 (Saturday)",
  "stella_gandhi": "Table 41 (Friday) & Table 41 (Saturday)",
  "teji_dhami": "Table 41 (Friday) & Table 41 (Saturday)",
  "alisha_gupta": "Table 42 (Friday) & Table 42 (Saturday)",
  "jaya_mehta": "Table 42 (Friday) & Table 42 (Saturday)",
  "swati_wadhwani": "Table 42 (Friday) & Table 42 (Saturday)",
  "ammu_susheela": "Table 42 (Friday) & Table 42 (Saturday)",
  "kunal_koka": "Table 42 (Friday) & Table 42 (Saturday)",
  "mounika_aramandla": "Table 42 (Friday) & Table 42 (Saturday)",
  "kimberly_croft": "Table 43 (Friday) & Table 43 (Saturday)",
  "shaun_keaton": "Table 43 (Friday) & Table 43 (Saturday)",
  "kristen_henderson": "Table 42 (Friday) & Table 42 (Saturday)",
  "jodi_bockenstette": "Table 42 (Friday) & Table 42 (Saturday)",
  "tony_cafazo": "Table 43 (Friday) & Table 43 (Saturday)",
  "alexis_munafo": "Table 43 (Friday) & Table 43 (Saturday)",
  "jahnavi_patel": "Table 43 (Friday) & Table 43 (Saturday)",
  "murali_alapati": "Table 43 (Friday) & Table 43 (Saturday)",
  "rita_khan": "Table 43 (Friday) & Table 43 (Saturday)",
  "steve_eppinghoff": "Table 43 (Friday) & Table 43 (Saturday)",
  "rtika_quintero": "Table 43 (Friday) & Table 43 (Saturday)",
  "mahi_rayasan": "Table 43 (Friday) & Table 43 (Saturday)",
  "anu_msfreen": "Table 44 (Friday) & Table 44 (Saturday)",
  "dani_moen": "Table 44 (Friday) & Table 44 (Saturday)",
  "amal_pillai": "Table 44 (Friday) & Table 44 (Saturday)",
  "aimee_simonetti": "Table 44 (Friday) & Table 44 (Saturday)",
  "liliana_quevedo": "Table 44 (Friday) & Table 44 (Saturday)",
  "inayat_masih": "Table 44 (Friday) & Table 44 (Saturday)",
  "brittany_belote": "Table 44 (Friday) & Table 44 (Saturday)",
  "erin_cowan": "Table 57 (Friday) & Table 57 (Saturday)",
  "johan_vako": "Table 44 (Friday) & Table 44 (Saturday)",
  "andre_sigismondo": "Table 44 (Friday) & Table 44 (Saturday)",
  "kamal_singh": "Table 45 (Friday) & Table 45 (Saturday)",
  "catie_liu": "Table 45 (Friday) & Table 45 (Saturday)",
  "syed_nishat": "Table 45 (Friday) & Table 45 (Saturday)",
  "matt_roth": "Table 45 (Friday) & Table 45 (Saturday)",
  "sarah_moran": "Table 56 (Friday) & Table 56 (Saturday)",
  "david_gonzalez": "Table 57 (Friday) & Table 57 (Saturday)",
  "malay_dey": "Table 45 (Friday only)",
  "vijay_gunuganti": "Table 45 (Friday only)",
  "susheel_kakde": "Table 45 (Friday only)",
  "rom mohan_kopparthi": "Table 45 (Friday only)",
  "nimisha_shukla": "Table 47 (Friday) & Table 47 (Saturday)",
  "sandeep_drunawat": "Table 47 (Friday) & Table 47 (Saturday)",
  "pesham_gor": "Table 47 (Friday) & Table 47 (Saturday)",
  "priti_mehta": "Table 47 (Friday) & Table 47 (Saturday)",
  "ahna_gor": "Table 47 (Friday) & Table 47 (Saturday)",
  "soniya_dave": "Table 47 (Friday) & Table 47 (Saturday)",
  "raj_pandya": "Table 47 (Friday) & Table 47 (Saturday)",
  "jayashree_holenarsipur": "Table 48 (Friday only)",
  "asha_mittar": "Table 48 (Friday only)",
  "bakul_patel": "Table 48 (Friday only)",
  "jaymin_patel": "Table 48 (Friday only)",
  "nita_patel": "Table 48 (Friday only)",
  "prem_mittar": "Table 51 (Saturday only)",
  "amrutha_reshi": "Table 49 (Saturday only)",
  "anvisha_upadhyaya": "Table 49 (Saturday only)",
  "kaival malav_shah": "Table 49 (Saturday only)",
  "devagna_mehta": "Table 49 (Saturday only)",
  "somya_majji": "Table 49 (Saturday only)",
  "yuvraj_kaushal": "Table 49 (Saturday only)",
  "swaramsi_katragadda": "Table 49 (Saturday only)",
  "rohan_chopra": "Table 49 (Saturday only)",
  "vipin_jain": "Table 49 (Saturday only)",
  "sarita_matta": "Table 49 (Saturday only)",
  "sohi_mistry": "Table 50 (Saturday only)",
  "narayan_reddy": "Table 50 (Saturday only)",
  "pani_akuthota": "Table 50 (Saturday only)",
  "ramaswamy_bathini": "Table 50 (Saturday only)",
  "sharat_kalvakota": "Table 50 (Saturday only)",
  "mahendra_matta": "Table 50 (Saturday only)",
  "venkat_muddana": "Table 50 (Saturday only)",
  "som_tandon": "Table 50 (Saturday only)",
  "sudhati_chennuru": "Table 50 (Saturday only)",
  "naga_madireddy": "Table 50 (Saturday only)",
  "rutvij bharatsinh_solanki": "Table 51 (Saturday only)",
  "sai manohar raju_obbani": "Table 51 (Saturday only)",
  "nisha_kumar": "Table 51 (Saturday only)",
  "mohan_brar": "Table 51 (Saturday only)",
  "jaspreet_chahal": "Table 51 (Saturday only)",
  "jaihindreddy_nalla": "Table 51 (Saturday only)",
  "vedanshi_shah": "Table 51 (Saturday only)",
  "sai revanth aashray_surapaneni": "Table 51 (Saturday only)",
  "sai kiran_kuchana": "Table 51 (Saturday only)",
  "poojajeet_khaira": "Table 51 (Saturday only)",
  "lahari_katta": "Table 51 (Saturday only)",
  "hesha reddy_abaka": "Table 51 (Saturday only)",
  "ajay_goud nattala": "Table 51 (Saturday only)",
  "lakshmi priyanka_chekka": "Table 51 (Saturday only)",
  "madhulika_jain": "Table 51 (Saturday only)",
  "sashwat_sriram": "Table 51 (Saturday only)",
  "samith_venkatesh": "Table 51 (Saturday only)",
  "kuldeep_yadav": "Table 51 (Saturday only)",
  "renuka sri sai_peddireddi": "Table 51 (Saturday only)",
  "prisha_mehta": "Table 52 (Saturday only)",
  "priyanka_kolli": "Table 52 (Saturday only)",
  "parneet_kaur": "Table 52 (Saturday only)",
  "surya_kodali": "Table 52 (Saturday only)",
  "srinihal_nallani": "Table 52 (Saturday only)",
  "aishwarya s_shikhare": "Table 52 (Saturday only)",
  "hemant_setya": "Table 52 (Saturday only)",
  "lipi_modha": "Table 52 (Saturday only)",
  "rohith_kode": "Table 52 (Saturday only)",
  "vaishnavi_patel": "Table 52 (Saturday only)",
  "sushmitha venkata_annadatha": "Table 53 (Saturday only)",
  "sanjana_boosa manmohan": "Table 53 (Saturday only)",
  "shrut_chaniyara": "Table 53 (Saturday only)",
  "saisreeram_kandula": "Table 53 (Saturday only)",
  "venkata sai harshabhargav_chenna": "Table 53 (Saturday only)",
  "jayesh kumar_patel": "Table 53 (Saturday only)",
  "uday kiran_kanike": "Table 59 (Friday) & Table 59 (Saturday)",
  "atula_paranjpe": "Table 53 (Friday) & Table 53 (Saturday)",
  "ravi_parikh": "Table 56 (Friday) & Table 56 (Saturday)",
  "mahesh_soni": "Table 53 (Friday) & Table 53 (Saturday)",
  "ashish_parikh": "Table 54 (Friday) & Table 54 (Saturday)",
  "stanley_zechariah": "Table 54 (Friday) & Table 54 (Saturday)",
  "gvp_prabhakar": "Table 54 (Friday) & Table 54 (Saturday)",
  "sachin_ravindran": "Table 56 (Friday) & Table 56 (Saturday)",
  "raagini_tv5": "Table 54 (Friday) & Table 54 (Saturday)",
  "sumathi_reddy": "Table 54 (Friday) & Table 54 (Saturday)",
  "rajiv_verma": "Table 54 (Friday) & Table 54 (Saturday)",
  "dhruv_bearelly": "Table 54 (Friday) & Table 54 (Saturday)",
  "dhanush_bearelly": "Table 54 (Friday) & Table 54 (Saturday)",
  "rajesh_kanumury": "Table 54 (Friday) & Table 54 (Saturday)",
  "volunteer2_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer3_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer4_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer5_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer6_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer7_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer8_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer9_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer11_volunteer": "Table 55 (Friday) & Table 55 (Saturday)",
  "volunteer12_volunteer": "Table 56 (Friday) & Table 56 (Saturday)",
  "volunteer13_volunteer": "Table 56 (Friday) & Table 56 (Saturday)",
  "volunteer14_volunteer": "Table 56 (Friday) & Table 56 (Saturday)",
  "volunteer15_volunteer": "Table 56 (Friday) & Table 56 (Saturday)",
  "volunteer16_volunteer": "Table 56 (Friday) & Table 56 (Saturday)",
  "dinesh_ahluwalia": "Table 56 (Friday) & Table 56 (Saturday)",
  "sam_sharma": "Table 56 (Friday) & Table 56 (Saturday)",
  "nikita_dhruv": "Table 60 (Friday) & Table 60 (Saturday)",
  "gopika_gangupantula": "Table 60 (Friday) & Table 60 (Saturday)",
  "vijaya_kodali": "Table 57 (Friday) & Table 57 (Saturday)",
  "maheswari_patel": "Table 57 (Friday) & Table 57 (Saturday)",
  "niranjan_patel": "Table 57 (Friday) & Table 57 (Saturday)",
  "dharna_shah": "Table 57 (Friday) & Table 57 (Saturday)",
  "kamalinder_kaur": "Table 57 (Friday) & Table 57 (Saturday)",
  "ajay_ghosh": "Table 57 (Friday) & Table 57 (Saturday)",
  "shital_parikh": "Table 58 (Saturday only)",
  "preeti_parikh": "Table 58 (Saturday only)",
  "viral_jain": "Table 58 (Saturday only)",
  "dinesh_thawrani": "Table 58 (Saturday only)",
  "rajul_gupta": "Table 58 (Saturday only)",
  "aakanksha_???": "Table 58 (Saturday only)",
  "krishna_reddy": "Table 58 (Saturday only)",
  "suma_reddy": "Table 58 (Saturday only)",
  "babu_gupta": "Table 58 (Saturday only)",
  "sadhna_gupta": "Table 58 (Saturday only)",
  "prabhat_sandhir": "Table 59 (Saturday only)",
  "sanjay_sandhir": "Table 59 (Saturday only)",
  "purvansh_bhatia": "Table 59 (Saturday only)",
  "prithi_dathi": "Table 59 (Saturday only)",
  "richa_sood": "Table 59 (Saturday only)",
  "gururau_sudarshan": "Table 59 (Saturday only)",
  "kamini_patel": "Table 59 (Saturday only)",
  "abhijit_desai": "Table 59 (Saturday only)",
  "kalyanram naidu_botsa": "Table 59 (Saturday only)",
  "suhas_parray": "Table 60 (Friday only)",
  "sudhakar_veeravalli": "Table 60 (Friday only)",
  "fahmida_shaik": "Table 60 (Friday) & Table 60 (Saturday)",
  "padma_nadella": "Table 60 (Friday) & Table 60 (Saturday)",
  "ravi_jahagirdar": "Table 60 (Friday) & Table 60 (Saturday)",
  "shervani_patel": "Table 60 (Friday) & Table 60 (Saturday)",
  "mita_morar": "Table 60 (Friday) & Table 60 (Saturday)",
  "kamal_morar, md, mba": "Table 60 (Friday) & Table 60 (Saturday)",
  "venkata_raju": "Table 60 (Friday) & Table 60 (Saturday)",
  "jessie_torres": "Table 60 (Friday) & Table 60 (Saturday)",
  "ati_gupta": "Table 61 (Friday) & Table 61 (Saturday)",
  "anand_gupta": "Table 61 (Friday) & Table 61 (Saturday)",
  "sumita_govil": "Table 61 (Friday) & Table 61 (Saturday)",
  "brenda_grogan": "Table 61 (Friday) & Table 61 (Saturday)",
  "ghizlane_b": "Table 61 (Friday) & Table 61 (Saturday)",
  "sheetal_patel": "Table 61 (Friday) & Table 61 (Saturday)",
  "suresh_bodiwala": "Table 61 (Friday) & Table 61 (Saturday)",
  "damodhar_patel": "Table 62 (Friday) & Table 62 (Saturday)",
  "amit_sood": "Table 62 (Friday) & Table 62 (Saturday)",
  "srilashmi_pisati": "Table 62 (Friday) & Table 62 (Saturday)",
  "neetu_verma": "Table 62 (Friday) & Table 62 (Saturday)",
  "siya_verma": "Table 62 (Friday) & Table 62 (Saturday)",
  "santhi priya_yalamanchili": "Table 62 (Friday) & Table 62 (Saturday)",
  "nandini_patel": "Table 62 (Friday) & Table 62 (Saturday)",
  "shashank_raj": "Table 62 (Friday) & Table 62 (Saturday)",
  "vijaya_prabhakar": "Table 63 (Friday) & Table 63 (Saturday)",
  "vk_raju": "Table 63 (Friday) & Table 63 (Saturday)",
  "lata_patel": "Table 63 (Friday) & Table 63 (Saturday)",
  "bob_erramilli": "Table 63 (Friday) & Table 63 (Saturday)",
  "ashok_veeragandham": "Table 63 (Friday) & Table 63 (Saturday)",
  "ram_saladi": "Table 63 (Friday) & Table 63 (Saturday)",
  "indira_saladi": "Table 63 (Friday) & Table 63 (Saturday)",
  "sreedhar_samudrala": "Table 63 (Friday) & Table 63 (Saturday)",
  "rajbir_minhas": "Table 63 (Friday) & Table 63 (Saturday)",
  "renu_minhas": "Table 64 (Friday) & Table 64 (Saturday)",
  "leena_gupta": "Table 64 (Friday) & Table 64 (Saturday)",
  "annu_terkonda": "Table 64 (Friday) & Table 64 (Saturday)",
  "kirti_chakote": "Table 64 (Friday) & Table 64 (Saturday)",
  "v.k._raju": "Table 64 (Friday) & Table 64 (Saturday)",
  "bertika_quintero": "Table 64 (Friday) & Table 64 (Saturday)",
  "nikhita_dhruv": "Table 64 (Friday) & Table 64 (Saturday)",
  "nalini_kanumury": "Table 64 (Friday) & Table 64 (Saturday)",
  "asha_khurana": "Table 64 (Friday) & Table 64 (Saturday)",
  "vikas_khurana": "Table 64 (Friday) & Table 64 (Saturday)",
  "parth_modi": "Table 65 (Friday) & Table 65 (Saturday)",
  "vriti_khurana": "Table 65 (Friday) & Table 65 (Saturday)",
  "preeti_saran": "Table 65 (Friday) & Table 65 (Saturday)",
  "lakmali_ranathunga": "Table 65 (Friday) & Table 65 (Saturday)",
  "rejith_paily": "Table 65 (Friday) & Table 65 (Saturday)",
  "ritesh_bajaj": "Table 65 (Friday) & Table 65 (Saturday)",
  "suresh_devnani": "Table 65 (Friday) & Table 65 (Saturday)",
  "smitha_paily": "Table 65 (Friday) & Table 65 (Saturday)",
  "sudha_peddana": "Table 65 (Friday) & Table 65 (Saturday)",
  "ramesh_khurana": "Table 65 (Friday) & Table 65 (Saturday)",
  "raghu_terkonda": "Table 66 (Friday) & Table 66 (Saturday)",
  "trisha_paily": "Table 66 (Friday) & Table 66 (Saturday)",
  "zeeshan_mansuri": "Table 66 (Friday) & Table 66 (Saturday)",
  "praveena_duggi": "Table 66 (Friday) & Table 66 (Saturday)",
  "mukund_dole": "Table 66 (Friday) & Table 66 (Saturday)",
  "vishwa_patel": "Table 66 (Friday) & Table 66 (Saturday)",
  "mansi_gosain": "Table 66 (Friday) & Table 66 (Saturday)",
  "krishna_prasanna": "Table 66 (Friday) & Table 66 (Saturday)",
  "raj_verma": "Table 66 (Friday) & Table 66 (Saturday)",
  "aruna_pitchika": "Table 66 (Friday) & Table 66 (Saturday)",
  "ravishankar_konchada": "Table 67 (Friday) & Table 67 (Saturday)",
  "ravinder_surakanti": "Table 67 (Friday) & Table 67 (Saturday)",
  "kaushal_dholakia": "Table 67 (Friday) & Table 67 (Saturday)",
  "mahendra_panchal": "Table 67 (Friday) & Table 67 (Saturday)",
  "sonia_samtani": "Table 67 (Friday) & Table 67 (Saturday)",
  "daniel_jerez": "Table 67 (Friday) & Table 67 (Saturday)",
  "pooja_goradia": "Table 67 (Friday) & Table 67 (Saturday)",
  "akhil_gupta": "Table 67 (Friday) & Table 67 (Saturday)",
  "deepthi_narala": "Table 67 (Friday) & Table 67 (Saturday)",
  "leela_krottapalli": "Table 67 (Friday) & Table 67 (Saturday)",
  "bilal_pandit": "Table 68 (Friday) & Table 68 (Saturday)",
  "vaijinath_chakote": "Table 68 (Friday) & Table 68 (Saturday)",
  "ranga_reddy": "Table 68 (Friday) & Table 68 (Saturday)",
  "amik_patel": "Table 68 (Friday) & Table 68 (Saturday)",
  "sunil_kaza": "Table 68 (Friday) & Table 68 (Saturday)",
  "ronee_terry": "Table 68 (Friday) & Table 68 (Saturday)",
  "vasu_singh": "Table 68 (Friday) & Table 68 (Saturday)",
  "disha_singla": "Table 68 (Friday) & Table 68 (Saturday)",
  "raghu_lollabhattu": "Table 68 (Friday) & Table 68 (Saturday)",
  "jyothi_lollabhattu": "Table 68 (Friday) & Table 68 (Saturday)",
  "shromona_mukherjee": "Table 69 (Friday) & Table 69 (Saturday)",
  "zeenat_ali": "Table 69 (Friday) & Table 69 (Saturday)",
  "aparajita_spencer": "Table 69 (Friday) & Table 69 (Saturday)",
  "grey_spencer": "Table 69 (Friday) & Table 69 (Saturday)",
  "shibani_chakrabarty": "Table 69 (Friday) & Table 69 (Saturday)",
  "nandini_shah": "Table 69 (Friday) & Table 69 (Saturday)",
  "kaval_shah": "Table 69 (Friday) & Table 69 (Saturday)",
  "sherli_brown": "Table 69 (Friday) & Table 69 (Saturday)",
  "raghu_juvadi": "Table 69 (Friday) & Table 69 (Saturday)",
  "mamta_juvadi": "Table 69 (Friday) & Table 69 (Saturday)",
  "sagar_galwakar": "Table 70 (Friday) & Table 70 (Saturday)",
  "harshith_eadara": "Table 70 (Friday) & Table 70 (Saturday)",
  "liza_flatley": "Table 70 (Friday) & Table 70 (Saturday)",
  "vasavi_mudireddy": "Table 70 (Friday) & Table 70 (Saturday)",
  "neelam_sehgal": "Table 70 (Friday) & Table 70 (Saturday)",
  "appaji_rayi": "Table 70 (Friday) & Table 70 (Saturday)",
  "mohammed t_hussain": "Table 70 (Friday) & Table 70 (Saturday)",
  "sromona_mukherjee": "Table 70 (Friday) & Table 70 (Saturday)",
  "ganesh_kakarlapudi": "Table 70 (Friday) & Table 70 (Saturday)",
  "vipan_nikore": "Table 70 (Friday) & Table 70 (Saturday)",
  "sabrina_beiruti": "Table 71 (Friday) & Table 71 (Saturday)",
  "indraneel_reddy": "Table 71 (Friday) & Table 71 (Saturday)",
  "poojitha_velluri": "Table 71 (Friday) & Table 71 (Saturday)",
  "john_maeglin": "Table 71 (Friday) & Table 71 (Saturday)",
  "balvant_arora": "Table 71 (Friday) & Table 71 (Saturday)"
};
